### ISSUE TITLE
Better communication of missing location data

### ISSUE THREAD

**Issue by geobrando** [code-for-portland-archive/trailheadit#27]
Was checking out traileditor.org for the first time and have a question.

I found trailheads located on null island, which wasn't apparent until I zoomed out and then also noticed `0.0,0.0` in the bottom left-hand corner.  Since it appears trailhead data is editable anyone, is the thought to accept photos without location and then let anyone who may recognize the photo improve the data (including adding missing location)?

For trailheads missing location data, it would be less confusing to new users if the map was not displayed on load.  Or alternatively it could be made clear perhaps by loading the marker with a pop-up alerting the user that location data is absent and desired.  These should also not be displayed on the main map.

http://www.traileditor.org/trailheads/958
http://www.traileditor.org/trailheads/957
http://www.traileditor.org/trailheads/959
http://www.traileditor.org/trailheads/map#22/0.00000/0.00000

**Comment by hollocherdale** [comment]
If photos contain GPS information (contained in the exit data), then that will be automatically stored as that trailhead's location. Some devices strip this information, so we added the convenience to edit the location using a map as a second option. Certainly, people could also improve/fix the location if it was inaccurate.

I agree that we should not display anything with 0,0 coordinates. In fact, we could probably leave those as null values instead of 0's.

When people do submit their trailheads (via email) with no gps coordinates, they do get a special response indicating that the position was missing, but so far that is the only response. We could probably create a whole 'null island' page for users to quickly help clean up the trailheads.

**Comment by jmoe** [comment]
Agree that it would be good to provide a more clear message for Trailheads at [0,0] maybe even an appeal to the effect of "No location data. Click Edit to provide the location."
